### ISSUE TITLE
one erro

### ISSUE THREAD

**Issue by SupperSpiderMan** [zhu733756/regex_trainer#2]
Connected to pydev debugger (build 193.5233.109)
2020-05-04 15:25:59 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: scrapybot)
2020-05-04 15:25:59 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.5, cssselect 1.1.0, parsel 1.5.0, w3lib 1.21.0, Twisted 19.10.0, Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Windows-7-6.1.7601-SP1
2020-05-04 15:25:59 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2020-05-04 15:25:59 [scrapy.crawler] INFO: Overridden settings:
{'DEPTH_LIMIT': 3,
 'DOWNLOAD_DELAY': 1,
 'DOWNLOAD_TIMEOUT': 30,
 'SPIDER_MODULES': ['regex_trainer.spiders']}
2020-05-04 15:26:00 [scrapy.extensions.telnet] INFO: Telnet Password: 36871d73ba5bd932
2020-05-04 15:26:00 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing BlpImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing BmpImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing BufrStubImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing CurImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing DcxImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing DdsImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing EpsImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing FitsStubImagePlugin
2020-05-04 15:26:00 [PIL.Image] DEBUG: Importing FliImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing FpxImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing FtexImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing GbrImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing GifImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing GribStubImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing Hdf5StubImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing IcnsImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing IcoImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing ImImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing ImtImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing IptcImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing JpegImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing Jpeg2KImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing McIdasImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing MicImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing MpegImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing MpoImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing MspImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PalmImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PcdImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PcxImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PdfImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PixarImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PngImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PpmImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing PsdImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing SgiImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing SpiderImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing SunImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing TgaImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing TiffImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing WebPImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing WmfImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing XbmImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing XpmImagePlugin
2020-05-04 15:26:01 [PIL.Image] DEBUG: Importing XVThumbImagePlugin
2020-05-04 15:26:15 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'regex_trainer.middlewares.regex_spider_middlewares.UrlTextFilterMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'regex_trainer.middlewares.regex_spider_middlewares.UrlDateFilterMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'regex_trainer.middlewares.regex_spider_middlewares.WebsiteDownloaderMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-05-04 15:26:15 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-05-04 15:26:16 [scrapy.middleware] INFO: Enabled item pipelines:
['regex_trainer.pipelines.regex_spider_pipelines.RegexSpiderPipeline']
2020-05-04 15:26:16 [scrapy.core.engine] INFO: Spider opened
2020-05-04 15:26:16 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-05-04 15:26:16 [regex_trainer] INFO: UrlDateFilterMiddleware opened: regex_trainer
2020-05-04 15:26:16 [regex_trainer] INFO: Spider opened: regex_trainer
2020-05-04 15:26:16 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-05-04 15:26:17 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jfdaily.com/home> (referer: None)
2020-05-04 15:26:26 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.jfdaily.com/home> (referer: None)
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\scrapy\utils\defer.py", line 117, in iter_errback
    yield next(it)
  File "D:\Python37\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "D:\Python37\lib\site-packages\scrapy\utils\python.py", line 345, in __next__
    return next(self.data)
  File "D:\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "D:\Python37\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "D:\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "D:\Python37\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "D:\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "D:\Python37\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "D:\Python37\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Python37\lib\site-packages\scrapy\core\spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "F:\爬虫项目\regex_trainer-master\regex_trainer\spiders\base_crawlspider.py", line 55, in _parse_response
    for request_or_item in self._requests_to_follow(response):
  File "F:\爬虫项目\regex_trainer-master\regex_trainer\spiders\regex_trainer.py", line 107, in _requests_to_follow
    yield rule.process_request(r)
TypeError: _identity_process_request() missing 1 required positional argument: 'response'
2020-05-04 15:26:27 [scrapy.core.engine] INFO: Closing spider (finished)
2020-05-04 15:26:27 [regex_trainer] INFO: finish crawl: 解放网
解放网 article_regex is 
2020-05-04 15:26:27 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 300,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 9249,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 10.317591,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 5, 4, 7, 26, 27, 72440),
 'log_count/DEBUG': 46,
 'log_count/ERROR': 1,
 'log_count/INFO': 13,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/TypeError': 1,
 'start_time': datetime.datetime(2020, 5, 4, 7, 26, 16, 754849)}
2020-05-04 15:26:27 [scrapy.core.engine] INFO: Spider closed (finished)
2020-05-04 15:26:27 [regex_trainer] DEBUG: save item:None
2020-05-04 15:26:27 [regex_trainer] DEBUG: save item:None

Process finished with exit code -1

**Comment by zhu733756** [comment]
没有找到这个bug，你看下你的环境以及启动命令行
![image](https://user-images.githubusercontent.com/38685176/80951588-c26e4a80-8e2a-11ea-9279-e803173477eb.png)
![image](https://user-images.githubusercontent.com/38685176/80951624-cdc17600-8e2a-11ea-95ef-8004fe156a80.png)
按照报错的位置，是在找不出问题，上面那个是我改写的方法，下面这个是crawlspider的方法。
测试了几遍，我这边并没有这个问题。

**Comment by SupperSpiderMan** [comment]
修改前：
.....
yield rule.process_request(r)
报错：
File "F:\爬虫项目\regex_trainer-master\regex_trainer\spiders\regex_trainer.py", line 107, in _requests_to_follow
    yield rule.process_request(r)
TypeError: _identity_process_request() missing 1 required positional argument: 'response'

修改后：
yield rule.process_request(r, response)
没有报错

**Comment by zhu733756** [comment]
好吧 官方Scrapy==1.6.0包里面没有response参数，有可能我们的scrapy版本不一样 感谢

**Comment by SupperSpiderMan** [comment]
yeah
